# Generated by Django 5.1.2 on 2024-10-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0004_userprofile_gender_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_info',
        ),
    ]
