# Generated by Django 5.1.2 on 2024-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0005_remove_userprofile_billing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval')], default='active', max_length=10),
        ),
    ]
