# Generated by Django 5.1.2 on 2024-11-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0010_remove_lesson_video_remove_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitevisitor.course'),
        ),
    ]
