# Generated by Django 5.1.2 on 2024-11-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0015_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='primary_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_lesson', to='sitevisitor.lessonvideo'),
        ),
    ]
