# Generated by Django 5.1.2 on 2024-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0018_userprofile_date_of_birth_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_order'),
        ),
    ]
