# Generated by Django 5.1.2 on 2024-11-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0019_alter_module_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowatchrecord',
            name='video_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitevisitor.lessonvideo'),
        ),
        migrations.AlterField(
            model_name='videowatchrecord',
            name='watch_time',
            field=models.PositiveIntegerField(default=0, help_text='Time spent watching video in seconds'),
        ),
    ]
