# Generated by Django 5.1.2 on 2024-11-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0020_alter_videowatchrecord_video_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='title',
            field=models.CharField(default='Untitled Video', max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
