# Generated by Django 5.1.2 on 2024-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0021_lessonvideo_title_alter_lessonvideo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='video_type',
            field=models.CharField(choices=[('local', 'Local'), ('youtube', 'YouTube')], default='local', max_length=10),
        ),
    ]
