# Generated by Django 5.1.2 on 2024-11-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0022_lessonvideo_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
