# Generated by Django 5.1.2 on 2024-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0027_alter_video_options_alter_video_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('local', 'Local')], max_length=10),
        ),
    ]
