# Generated by Django 5.1.2 on 2024-11-08 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0028_alter_video_video_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_course_order',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_videos', to='sitevisitor.lesson'),
        ),
    ]
