# Generated by Django 5.1.2 on 2024-11-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0034_course_price_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvideo',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
