# Generated by Django 5.1.2 on 2024-11-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0036_alter_lessonvideo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvideo',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
