# Generated by Django 5.1.2 on 2024-11-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0037_alter_lessonvideo_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonvideo',
            old_name='video',
            new_name='video_file',
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_video_files', to='sitevisitor.lesson'),
        ),
    ]
