# Generated by Django 5.1.2 on 2024-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0038_rename_video_lessonvideo_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.FileField(blank=True, help_text='Upload a PDF file for the course curriculum.', null=True, upload_to='course_curriculums/'),
        ),
    ]
