# Generated by Django 5.1.2 on 2024-11-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0039_course_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_locked',
        ),
    ]
