# Generated by Django 5.1.2 on 2024-11-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0040_remove_lesson_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
