# Generated by Django 5.1.2 on 2024-11-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0043_remove_course_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_courses', to='sitevisitor.userprofile'),
        ),
    ]
