# Generated by Django 5.1.2 on 2024-11-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0049_videocompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
        migrations.DeleteModel(
            name='VideoCompletion',
        ),
    ]
