# Generated by Django 5.1.2 on 2024-11-13 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0050_remove_enrollment_progress_delete_videocompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='mentor_profiles/')),
                ('bio', models.TextField(blank=True, help_text='Short bio of the mentor.', null=True)),
                ('skills', models.TextField(blank=True, help_text='List of skills, separated by commas.', null=True)),
                ('experience', models.TextField(blank=True, help_text="Details about the mentor's experience.", null=True)),
                ('awards_and_recognitions', models.TextField(blank=True, help_text='Awards and recognitions received by the mentor.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
