# Generated by Django 5.1.2 on 2024-11-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0051_mentorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='profile_image',
        ),
    ]
