# Generated by Django 5.1.2 on 2024-11-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0052_remove_mentorprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='awards_and_recognitions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
