# Generated by Django 5.1.2 on 2024-11-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0055_alter_mentorprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
