# Generated by Django 5.1.2 on 2024-11-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0056_enrollment_progress_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sitevisitor.lesson'),
        ),
        migrations.DeleteModel(
            name='LessonVideo',
        ),
    ]
