# Generated by Django 5.1.2 on 2024-11-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisitor', '0062_promotion_created_at_promotion_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='promotion',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitevisitor.course'),
        ),
    ]
